apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados
spec:
  accessModes:
    -ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: database
  labels: 
    app: mysql
  spec: 
    selector: 
      matchLabels:
        app: mysql
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: mysql
      spec:
        containers: 
          - name: mysql
            image: lidsarti/projeto-database
            args:
            - "--ignore-db-dir=lost+found"
            imagePullPolicy: Always
            ports:
              - containerPorts: 3360
      volumeMounts:
      - name: mysql-dados
        mountPath: /var/lib/mysql/
      volumes:
      - name: mysql-dados
        PersistentVolumeClaim:
        claimName: mysql-dados

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: database
  labels: 
    app: php
  spec: 
    selector: 
      matchLabels:
        app: php
    replicas: 6
    template: 
      metadata: 
        labels: 
          app: php
      spec:
        containers: 
          - name: php
            image: lidsarti/projeto-backend
            imagePullPolicy: Always
            ports:
              - containerPorts: 80